#!/usr/bin/env bash
# Refresh vendor/ from the published source of every dependency the baked
# platform pins.
#
# Why vendor at all: the image must render with no registry reachable, and an
# offline-by-warm-cache image is offline only by luck (D4). A vendored tree is
# offline by construction, reviewable in a diff, and about a tenth the size of
# the cache it replaces.
#
# Where the bytes come from: this stages a copy of platform/ with its local
# replacements REMOVED, evaluates it against a private, empty CUE cache, and
# copies each module out of <cache>/mod/extract/. That directory is the
# published module zip unpacked, so nothing here can come from a working copy
# in this workspace. Vendoring from a sibling checkout instead would silently
# ship unpublished bytes.
#
# Running this is the one act in the repo that touches a registry, and it is
# deliberate. Nothing in the build or the image does.
set -euo pipefail

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

: "${CUE_REGISTRY:=opmodel.dev=ghcr.io/open-platform-model,testing.opmodel.dev=ghcr.io/open-platform-model,registry.cue.works}"
export CUE_REGISTRY

# The CUE module cache is created read-only (0444 files, 0555 dirs), so it
# cannot be removed without making it writable first.
work=$(mktemp -d -t opm-suite-vendor-XXXXXX)
cleanup() {
	chmod -R u+w "$work" 2>/dev/null || true
	rm -rf "$work"
}
trap cleanup EXIT

cache="$work/cache"
stage="$work/platform"
mkdir -p "$cache"
cp -r platform "$stage"
# The whole point: resolve from the registry, not from vendor/.
rm -f "$stage/cue.mod/local-module.cue"

echo "resolving the platform's dependency closure from $CUE_REGISTRY" >&2
(
	cd "$stage"
	CUE_CACHE_DIR="$cache" cue vet ./...
)

# Every dependency the platform declares, tidied form, transitive pins included.
pins=$(cue export platform/cue.mod/module.cue --out json |
	jq -r '.deps | to_entries[] | "\(.key) \(.value.v)"' | sort)

rm -rf vendor
mkdir -p vendor

while read -r dep version; do
	[ -n "$dep" ] || continue
	# "opmodel.dev/core@v2" + "v2.0.0-alpha.10" -> extract path
	# "opmodel.dev/core@v2.0.0-alpha.10". The vendor tree keeps the MAJOR
	# path so the replacements in cue.mod/local-module.cue never move; the
	# exact version lives in vendor/VERSIONS.
	src="$cache/mod/extract/${dep%@*}@${version}"
	dest="vendor/${dep}"
	if [ ! -d "$src" ]; then
		echo "no extracted source for $dep $version at $src" >&2
		echo "the platform declares it but evaluating the platform never loaded it" >&2
		exit 1
	fi
	mkdir -p "$(dirname "$dest")"
	cp -r "$src" "$dest"
	chmod -R u+w "$dest"
	echo "vendored $dep $version" >&2
done <<<"$pins"

{
	echo "# Generated by 'task vendor:sync'. Do not edit."
	echo "#"
	echo "# Every dependency of platform/cue.mod/module.cue, vendored from the published"
	echo "# module source. Each entry is served from vendor/<module path> by the local"
	echo "# replacements in platform/cue.mod/local-module.cue and bundle/cue.mod/local-module.cue."
	echo "#"
	echo "# module	version"
	while read -r dep version; do
		[ -n "$dep" ] || continue
		printf '%s\t%s\n' "$dep" "$version"
	done <<<"$pins"
} >vendor/VERSIONS

echo >&2
echo "vendor/ is $(du -sh vendor | cut -f1)" >&2
